In [33]:
import numpy as np
import pandas as pd
df=pd.read_csv('heart_clean2.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg     thalach  exang  oldpeak  \
0      52    1   0     125.0   212    0      1.0  168.000000      0      1.0   
1      53    1   0     140.0   203    1      0.0  155.000000      1      3.1   
2      70    1   0     145.0   174    0      1.0  125.000000      1      2.6   
3      61    1   0     148.0   203    0      1.0  149.102539      0      0.0   
4      62    0   0     138.0   294    1      1.0  106.000000      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...         ...    ...      ...   
1020   59    1   1     140.0   221    0      1.0  164.000000      1      0.0   
1021   60    1   0     125.0   258    0      0.0  141.000000      1      2.8   
1022   47    1   0     110.0   275    0      0.0  118.000000      1      1.0   
1023   50    0   0     110.0   254    0      0.0  159.000000      0      0.0   
1024   54    1   0     120.0   188    0      1.0  113.000000      0      1.4   

      slope   ca  thal  target  
0         2  2.0   3.0       0  
1         0  0.0   3.0       0  
2         0  0.0   3.0       0  
3         2  1.0   3.0       0  
4         1  3.0   2.0       0  
...     ...  ...   ...     ...  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0  

[1025 rows x 14 columns]

In [34]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg     thalach  exang  oldpeak  \
0   52    1   0     125.0   212    0      1.0  168.000000      0      1.0   
1   53    1   0     140.0   203    1      0.0  155.000000      1      3.1   
2   70    1   0     145.0   174    0      1.0  125.000000      1      2.6   
3   61    1   0     148.0   203    0      1.0  149.102539      0      0.0   
4   62    0   0     138.0   294    1      1.0  106.000000      0      1.9   

   slope   ca  thal  target  
0      2  2.0   3.0       0  
1      0  0.0   3.0       0  
2      0  0.0   3.0       0  
3      2  1.0   3.0       0  
4      1  3.0   2.0       0

In [35]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0

In [36]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [37]:
df.shape

(1025, 14)

In [38]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [39]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]], shape=(1025, 13))

In [40]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0], shape=(1025,))

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[59.,  1.,  1., ...,  2.,  0.,  2.],
       [58.,  1.,  0., ...,  1.,  3.,  3.],
       [44.,  0.,  2., ...,  1.,  1.,  2.],
       ...,
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [43.,  1.,  0., ...,  2.,  0.,  3.],
       [52.,  1.,  0., ...,  2.,  1.,  2.]], shape=(717, 13))

In [42]:
x_test.ndim

2

In [43]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test


array([[ 0.84237819, -1.55379719, -0.92619093, ...,  0.97708096,
        -0.72641166, -0.53812812],
       [-0.14794181, -1.55379719,  0.98482748, ...,  0.97708096,
        -0.72641166, -3.82185458],
       [ 0.0721293 ,  0.64358464, -0.92619093, ..., -0.65214474,
         0.22228991,  1.10373511],
       ...,
       [ 1.72266262,  0.64358464,  0.98482748, ..., -0.65214474,
         0.22228991,  1.10373511],
       [ 1.39255596,  0.64358464, -0.92619093, ..., -0.65214474,
         1.17099147, -0.53812812],
       [ 1.0624493 ,  0.64358464,  0.98482748, ...,  0.97708096,
        -0.72641166, -0.53812812]], shape=(308, 13))

In [44]:
x_test

array([[ 0.84237819, -1.55379719, -0.92619093, ...,  0.97708096,
        -0.72641166, -0.53812812],
       [-0.14794181, -1.55379719,  0.98482748, ...,  0.97708096,
        -0.72641166, -3.82185458],
       [ 0.0721293 ,  0.64358464, -0.92619093, ..., -0.65214474,
         0.22228991,  1.10373511],
       ...,
       [ 1.72266262,  0.64358464,  0.98482748, ..., -0.65214474,
         0.22228991,  1.10373511],
       [ 1.39255596,  0.64358464, -0.92619093, ..., -0.65214474,
         1.17099147, -0.53812812],
       [ 1.0624493 ,  0.64358464,  0.98482748, ...,  0.97708096,
        -0.72641166, -0.53812812]], shape=(308, 13))

In [45]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[123,  36],
       [ 17, 132]])

In [47]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.827922077922078